//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeachuApp.Resx {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeachuApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available: .
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available Bathing Establishments.
        /// </summary>
        public static string AvailableTitle {
            get {
                return ResourceManager.GetString("AvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Available Umbrellas.
        /// </summary>
        public static string AvailUmbrellaLabel {
            get {
                return ResourceManager.GetString("AvailUmbrellaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Establishment Name:.
        /// </summary>
        public static string BathNameLabel {
            get {
                return ResourceManager.GetString("BathNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contacts.
        /// </summary>
        public static string ContactsTitle {
            get {
                return ResourceManager.GetString("ContactsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Edit Profile.
        /// </summary>
        public static string EditProfileLabel {
            get {
                return ResourceManager.GetString("EditProfileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connection error.
        /// </summary>
        public static string ErrorConn {
            get {
                return ResourceManager.GetString("ErrorConn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Coordinates not available.
        /// </summary>
        public static string ErrorCoord {
            get {
                return ResourceManager.GetString("ErrorCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Not supported device: .
        /// </summary>
        public static string ErrorDevice {
            get {
                return ResourceManager.GetString("ErrorDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a GPS disabled: .
        /// </summary>
        public static string ErrorGps {
            get {
                return ResourceManager.GetString("ErrorGps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a You must insert a number: .
        /// </summary>
        public static string ErrorNr {
            get {
                return ResourceManager.GetString("ErrorNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Operation failed.
        /// </summary>
        public static string ErrorOperation {
            get {
                return ResourceManager.GetString("ErrorOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Insufficient permits: .
        /// </summary>
        public static string ErrorPerm {
            get {
                return ResourceManager.GetString("ErrorPerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to make a phone call: .
        /// </summary>
        public static string ErrorPh {
            get {
                return ResourceManager.GetString("ErrorPh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unable to get position: .
        /// </summary>
        public static string ErrorPosition {
            get {
                return ResourceManager.GetString("ErrorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Invalid values.
        /// </summary>
        public static string ErrorValues {
            get {
                return ResourceManager.GetString("ErrorValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a General Info.
        /// </summary>
        public static string GeneralInfoTitle {
            get {
                return ResourceManager.GetString("GeneralInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hi.
        /// </summary>
        public static string HelloLabel {
            get {
                return ResourceManager.GetString("HelloLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Info Bathing Establishment.
        /// </summary>
        public static string InfoBathTitle {
            get {
                return ResourceManager.GetString("InfoBathTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bathing Establishments.
        /// </summary>
        public static string ListBathsTitle {
            get {
                return ResourceManager.GetString("ListBathsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login Operators.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login Data.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E-mail:.
        /// </summary>
        public static string MailLabel {
            get {
                return ResourceManager.GetString("MailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a example@example.com.
        /// </summary>
        public static string MailSampleLabel {
            get {
                return ResourceManager.GetString("MailSampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open Map.
        /// </summary>
        public static string MapLabel {
            get {
                return ResourceManager.GetString("MapLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Successiful operation.
        /// </summary>
        public static string MsgOperation {
            get {
                return ResourceManager.GetString("MsgOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Congratulations.
        /// </summary>
        public static string MsgTitle {
            get {
                return ResourceManager.GetString("MsgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No available bathing establishments.
        /// </summary>
        public static string NobathLabel {
            get {
                return ResourceManager.GetString("NobathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Personal info.
        /// </summary>
        public static string PersonalTitle {
            get {
                return ResourceManager.GetString("PersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Phone.
        /// </summary>
        public static string PhoneLabel {
            get {
                return ResourceManager.GetString("PhoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Place:.
        /// </summary>
        public static string PlaceLabel {
            get {
                return ResourceManager.GetString("PlaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Place and Location.
        /// </summary>
        public static string PlaceTitle {
            get {
                return ResourceManager.GetString("PlaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exact Position:.
        /// </summary>
        public static string PositionLabel {
            get {
                return ResourceManager.GetString("PositionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Province:.
        /// </summary>
        public static string ProvinceLabel {
            get {
                return ResourceManager.GetString("ProvinceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Password:.
        /// </summary>
        public static string PswLabel {
            get {
                return ResourceManager.GetString("PswLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scrolldown to update.
        /// </summary>
        public static string ScrollLabel {
            get {
                return ResourceManager.GetString("ScrollLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search....
        /// </summary>
        public static string SearchBar {
            get {
                return ResourceManager.GetString("SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search nearby.
        /// </summary>
        public static string SearchNearButton {
            get {
                return ResourceManager.GetString("SearchNearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Search in a place.
        /// </summary>
        public static string SearchPlaceButton {
            get {
                return ResourceManager.GetString("SearchPlaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Login.
        /// </summary>
        public static string SigninButton {
            get {
                return ResourceManager.GetString("SigninButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sign Up.
        /// </summary>
        public static string SigniupButton {
            get {
                return ResourceManager.GetString("SigniupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Surname:.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nr. Of Umbrelllas:.
        /// </summary>
        public static string UmbrellaLabel {
            get {
                return ResourceManager.GetString("UmbrellaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Web Site:.
        /// </summary>
        public static string WebSiteLabel {
            get {
                return ResourceManager.GetString("WebSiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a www.example.com.
        /// </summary>
        public static string WebSiteSampleLabel {
            get {
                return ResourceManager.GetString("WebSiteSampleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Your Bathing Establishments.
        /// </summary>
        public static string YourBathsLabel {
            get {
                return ResourceManager.GetString("YourBathsLabel", resourceCulture);
            }
        }
    }
}
